name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Loading submodules
      run: git submodule update --init --recursive   
    - name: Work directory
      run: echo $PATH
      shell: bash
    - name: Loading secrets
      with:
        googleservices: ${{ secrets.googleservices }}
    - name: Build with Gradle 
      run: ./gradlew build
